// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD47f3ui8HnAzyZIHLmU4ea57_W72HxSBY',
    appId: '1:564934186228:web:55ea55043c88b48aef3aa1',
    messagingSenderId: '564934186228',
    projectId: 'temu-aksi',
    authDomain: 'temu-aksi.firebaseapp.com',
    storageBucket: 'temu-aksi.firebasestorage.app',
    measurementId: 'G-3ZRJM7LQMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBpeGYnM-AULjgOe-0bykskkQgpzVbSd0',
    appId: '1:564934186228:android:9fc36384f9e980bdef3aa1',
    messagingSenderId: '564934186228',
    projectId: 'temu-aksi',
    storageBucket: 'temu-aksi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO7A1n16AHN6MlW6j3s4y8yh7EjL5aBbU',
    appId: '1:564934186228:ios:edda941c1ed031dcef3aa1',
    messagingSenderId: '564934186228',
    projectId: 'temu-aksi',
    storageBucket: 'temu-aksi.firebasestorage.app',
    iosClientId: '564934186228-fbvnjgbi723st11b13ms39dfqf00dpo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.temuAksi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO7A1n16AHN6MlW6j3s4y8yh7EjL5aBbU',
    appId: '1:564934186228:ios:edda941c1ed031dcef3aa1',
    messagingSenderId: '564934186228',
    projectId: 'temu-aksi',
    storageBucket: 'temu-aksi.firebasestorage.app',
    iosClientId: '564934186228-fbvnjgbi723st11b13ms39dfqf00dpo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.temuAksi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD47f3ui8HnAzyZIHLmU4ea57_W72HxSBY',
    appId: '1:564934186228:web:6deb3fb9b5bbc0b9ef3aa1',
    messagingSenderId: '564934186228',
    projectId: 'temu-aksi',
    authDomain: 'temu-aksi.firebaseapp.com',
    storageBucket: 'temu-aksi.firebasestorage.app',
    measurementId: 'G-871ZQRXJJF',
  );

}